// prisma/seed.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const cdbs = [
    {
      id: 'b0d8f2f7-9a10-4a41-a1df-7ea1eecbfa01',
      name: 'CDB Banco Bradesco',
      issuer: 'Banco Bradesco',
      type: 'CDB',
      interestRate: 14.2,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2029-01-10T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 8000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '18c60e49-04b2-43fa-a5de-f1f5f7f41ab2',
      name: 'CDB Banco BTG',
      issuer: 'Banco BTG',
      type: 'CDB',
      interestRate: 102,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2026-03-20T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 2000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'ad8de4a1-2fc9-4e26-b83d-0cb02c9bb681',
      name: 'CDB Banco Original',
      issuer: 'Banco Original',
      type: 'CDB',
      interestRate: 12.7,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2027-08-12T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 6000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'f2d35dc1-ec93-4fc0-99e2-2aa6c7c38cb2',
      name: 'CDB Banco Safra',
      issuer: 'Banco Safra',
      type: 'CDB',
      interestRate: 13.9,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2029-05-25T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 7500,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'f4ec1992-63b7-4aa3-9b8d-73f24d61aa71',
      name: 'CDB Banco Pan',
      issuer: 'Banco Pan',
      type: 'CDB',
      interestRate: 110,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2027-02-18T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 1500,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '45215e67-52ab-4294-9b6a-5cdb6726ef42',
      name: 'CDB Banco Daycoval',
      issuer: 'Banco Daycoval',
      type: 'CDB',
      interestRate: 13.3,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2028-11-30T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 7000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'dff3dbcf-96cc-4342-91f0-1b33925a1792',
      name: 'CDB Banco BMG',
      issuer: 'Banco BMG',
      type: 'CDB',
      interestRate: 107,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2026-10-12T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 2500,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '4f1f4f33-9e2c-42bc-b9c2-e79a1cc08941',
      name: 'CDB Banco C6',
      issuer: 'Banco C6',
      type: 'CDB',
      interestRate: 12.2,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2027-04-30T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 5000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'f75f46c3-775c-47d7-a268-4174f1832514',
      name: 'CDB Banco Neon',
      issuer: 'Banco Neon',
      type: 'CDB',
      interestRate: 104,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2026-07-14T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 1000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '7b9b3f90-8b6b-4e9e-bc8e-58c28c84f1aa',
      name: 'CDB Banco Modal',
      issuer: 'Banco Modal',
      type: 'CDB',
      interestRate: 13.6,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2028-06-22T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 9000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'a1e5ef23-8a4f-4f6e-9c9b-9ff1a9f6eaaa',
      name: 'CDB Banco Votorantim',
      issuer: 'Banco Votorantim',
      type: 'CDB',
      interestRate: 108,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2026-09-15T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 3000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'e96f6f3f-e120-49e3-a0d0-9c72ae1f6a4c',
      name: 'CDB Banco ABC Brasil',
      issuer: 'Banco ABC Brasil',
      type: 'CDB',
      interestRate: 11.9,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2027-10-05T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 6000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '03c7f1fa-1a79-49e2-b84a-037d8eebd9dc',
      name: 'CDB Banco BS2',
      issuer: 'Banco BS2',
      type: 'CDB',
      interestRate: 105,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2026-01-01T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 1500,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '927b4293-ec61-4e43-9bd8-9f2703d59e9d',
      name: 'CDB Banco Banrisul',
      issuer: 'Banco Banrisul',
      type: 'CDB',
      interestRate: 13.0,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2028-03-14T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 8000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'c222d242-2f4e-4931-bec6-3c38a3a4fd21',
      name: 'CDB Banco Pine',
      issuer: 'Banco Pine',
      type: 'CDB',
      interestRate: 109,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2027-09-01T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 4000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '63416d4c-81d9-42c4-a5b1-28e03c9d74a5',
      name: 'CDB Banco Agibank',
      issuer: 'Banco Agibank',
      type: 'CDB',
      interestRate: 13.4,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2028-10-20T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 7000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'dbbdc7df-fef8-4ec7-a0c3-2744ea6ad8f4',
      name: 'CDB Banco Fibra',
      issuer: 'Banco Fibra',
      type: 'CDB',
      interestRate: 106,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2026-11-11T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 2000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'ec1937f6-b18a-4e26-944c-71862b086c62',
      name: 'CDB Banco Bocom BBM',
      issuer: 'Banco Bocom BBM',
      type: 'CDB',
      interestRate: 12.9,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2027-12-25T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 5000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '38b1f679-bfe4-4d3e-930c-ff90a7e2dd91',
      name: 'CDB Banco Western Union',
      issuer: 'Banco Western Union',
      type: 'CDB',
      interestRate: 101,
      interestType: 'Pós-fixado',
      indexer: 'CDI',
      maturityDate: new Date('2026-05-10T00:00:00.000Z'),
      liquidity: 'Diária',
      minimumInvestment: 3000,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: '798fb733-d4c4-4d92-ae4b-7207a83f5c25',
      name: 'CDB Banco Máxima',
      issuer: 'Banco Máxima',
      type: 'CDB',
      interestRate: 14.0,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2029-02-28T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 6500,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    {
      id: 'b4b1a9a5-2c3f-4e7d-9e7e-6c3f8a5e0b1e',
      name: 'CDB Banco ModalMais',
      issuer: 'Banco ModalMais',
      type: 'CDB',
      interestRate: 13.8,
      interestType: 'Prefixado',
      indexer: 'CDI',
      maturityDate: new Date('2028-07-17T00:00:00.000Z'),
      liquidity: 'No vencimento',
      minimumInvestment: 8500,
      taxation: 'IR',
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: null,
    },
    // +20 produtos similares abaixo (excluídos aqui por limite de espaço)
  ];

  for (const cdb of cdbs) {
    await prisma.fixedIncomeInvestment.upsert({
      where: { id: cdb.id },
      update: {},
      create: cdb,
    });
  }

  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
